name: Dynamic Environment Workflow

on:
  push

# Define your variable at the workflow level


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_LANDSCAPE: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
    
    # Correctly reference the 'env' context variable using expression syntax
    environment: ${{ env.AWS_LANDSCAPE }}
    
    steps:
      - name: Check Job Context
        run: |
          echo "The job is running in the '${{ job.environment }}' environment."
          echo "This value came from the AWS_LANDSCAPE variable."
